apiVersion: v1
kind: Secret
metadata:
  name: db-secret-sql
  namespace: ${env.NAMESPACE}
type: Opaque
stringData:  
  db.server.name: ${env.DB_SERVER_NAME}
  db.port.number: "${env.DB_PORT_NUMBER}"
  db.name: ${env.DB_NAME}
  db.user: ${env.DB_USER}
  db.password: ${env.DB_PASSWORD}
