apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
  name: cargo-tracker-cluster
  namespace: ${env.NAMESPACE}
spec:
  replicas: 1
  applicationImage: ${env.LOGIN_SERVER}/cargo-tracker:3.4.0
  pullPolicy: Always
  service:
    type: LoadBalancer
    port: 9080
  env:
  - name: DB_SERVER_NAME
    valueFrom:
      secretKeyRef:
        name: db-secret-sql
        key: db.server.name
  - name: DB_PORT_NUMBER
    valueFrom:
      secretKeyRef:
        name: db-secret-sql
        key: db.port.number
  - name: DB_NAME
    valueFrom:
      secretKeyRef:
        name: db-secret-sql
        key: db.name
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: db-secret-sql
        key: db.user
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-secret-sql
        key: db.password
